"""Command adapter for the durable workflow-state owner."""

from __future__ import annotations

import argparse
from typing import Any, Sequence

from coordinator.cli.outcome import OutcomeArgumentParser, emit, parse_invocation
from coordinator.routing.selector import STAGES
from coordinator.state.store import (
    AMBIGUITY_FACTORS,
    LAUNCH_STATES,
    ROLES,
    StateError,
    StateStore,
    execute_command,
)

NODE_UPDATE_STATUSES = ("pending", "ready", "running", "blocked", "done", "failed")


def _add_mutation_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--workflow-id", required=True)
    parser.add_argument("--session-file", required=True)
    parser.add_argument("--mutation-id", required=True)
    parser.add_argument("--expected-revision", required=True, type=int)


def _subcommand(subparsers: Any, name: str, *, mutate: bool = False) -> argparse.ArgumentParser:
    parser = subparsers.add_parser(name)
    if mutate:
        _add_mutation_arguments(parser)
    parser.add_argument("--json", action="store_true")
    return parser


def build_parser() -> argparse.ArgumentParser:
    parser = OutcomeArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    opened = _subcommand(sub, "session-open")
    opened.add_argument("--repo", required=True)
    opened.add_argument("--session-file", required=True)
    closed = _subcommand(sub, "session-close")
    closed.add_argument("--session-file", required=True)
    init = _subcommand(sub, "init")
    init.add_argument("--repo", required=True)
    task = init.add_mutually_exclusive_group(required=True)
    task.add_argument("--task")
    task.add_argument("--task-file")
    init.add_argument("--profile-file")
    init.add_argument("--session-file", required=True)
    init.add_argument("--mutation-id", required=True)
    listed = _subcommand(sub, "list")
    listed.add_argument("--repo")
    for name in ("status", "context", "next"):
        target = _subcommand(sub, name)
        target.add_argument("--workflow-id", required=True)
    reconcile = _subcommand(sub, "reconcile-mutation")
    reconcile.add_argument("--workflow-id", required=True)
    reconcile.add_argument("--mutation-id", required=True)
    reconcile.add_argument("--digest")
    _subcommand(sub, "controller-takeover", mutate=True)
    resume = _subcommand(sub, "resume", mutate=True)
    resume.add_argument("--message", required=True)

    apply_plan = _subcommand(sub, "plan-apply", mutate=True)
    manifest = apply_plan.add_mutually_exclusive_group(required=True)
    manifest.add_argument("--plan-json")
    manifest.add_argument("--plan-file")

    add = _subcommand(sub, "node-add", mutate=True)
    add.add_argument("--node-id", required=True)
    add.add_argument("--title", required=True)
    add.add_argument("--stage", choices=tuple(sorted(STAGES)), required=True)
    add.add_argument("--priority", type=int, default=50)
    add.add_argument("--dependency", action="append", default=[])
    add.add_argument("--write-scope", action="append", default=[])
    add.add_argument("--role", choices=ROLES, required=True)
    add.add_argument("--model")
    add.add_argument("--effort")
    add.add_argument("--acceptance", action="append", required=True)
    add.add_argument("--evidence", required=True)
    add.add_argument("--evidence-positive-proof-command", required=True)
    add.add_argument("--evidence-negative-proof-command", required=True)
    add.add_argument("--rationale", required=True)
    add.add_argument("--estimated-cost", type=float)
    add.add_argument("--objective", required=True)
    add.add_argument("--input", action="append", default=[])
    add.add_argument("--output", action="append", required=True)
    add.add_argument("--constraint", action="append", default=[])
    add.add_argument("--non-goal", action="append", default=[])
    add.add_argument("--requirement-id", action="append", default=[])
    add.add_argument("--open-question", action="append", default=[])
    add.add_argument("--breadth", type=int, required=True)
    add.add_argument("--change-surface", type=int, required=True)
    add.add_argument("--coupling", type=int, required=True)
    add.add_argument("--novelty", type=int, required=True)
    add.add_argument("--verification", type=int, required=True)
    for factor in AMBIGUITY_FACTORS:
        add.add_argument(f"--ambiguity-{factor}", dest=f"ambiguity_{factor}", type=int, required=True)
    add.add_argument("--complexity-rationale", required=True)
    refine = _subcommand(sub, "node-refine", mutate=True)
    refine.add_argument("--node-id", required=True)
    refinement = refine.add_mutually_exclusive_group(required=True)
    refinement.add_argument("--refinement-json")
    refinement.add_argument("--refinement-file")
    split = _subcommand(sub, "node-split", mutate=True)
    split_plan = split.add_mutually_exclusive_group(required=True)
    split_plan.add_argument("--plan-json")
    split_plan.add_argument("--plan-file")
    observe = _subcommand(sub, "node-observe", mutate=True)
    observe.add_argument("--node-id", required=True)
    observation = observe.add_mutually_exclusive_group(required=True)
    observation.add_argument("--observation-json")
    observation.add_argument("--observation-file")
    reconcile_graph = _subcommand(sub, "graph-reconcile", mutate=True)
    reconcile_proofs = reconcile_graph.add_mutually_exclusive_group(required=True)
    reconcile_proofs.add_argument("--proof-plan-json")
    reconcile_proofs.add_argument("--proof-plan-file")
    expand_graph = _subcommand(sub, "graph-expand-auto", mutate=True)
    expansion = expand_graph.add_mutually_exclusive_group(required=True)
    expansion.add_argument("--plan-json")
    expansion.add_argument("--plan-file")
    gate = _subcommand(sub, "judge-gate-add", mutate=True)
    gate.add_argument("--node-id", required=True)
    gate_plan = gate.add_mutually_exclusive_group(required=True)
    gate_plan.add_argument("--gate-json")
    gate_plan.add_argument("--gate-file")
    judge = _subcommand(sub, "judge-complete", mutate=True)
    judge.add_argument("--node-id", required=True)
    judge.add_argument("--verdict", choices=("pass", "fail"), required=True)
    judge_result = judge.add_mutually_exclusive_group()
    judge_result.add_argument("--result")
    judge_result.add_argument("--result-file")
    judge_evidence = judge.add_mutually_exclusive_group()
    judge_evidence.add_argument("--evidence")
    judge_evidence.add_argument("--evidence-file")
    next_iteration = judge.add_mutually_exclusive_group()
    next_iteration.add_argument("--next-iteration-proof-json")
    next_iteration.add_argument("--next-iteration-proof-file")
    judge.add_argument("--actual-cost", type=float)
    route = _subcommand(sub, "node-route", mutate=True)
    route.add_argument("--node-id", required=True)
    route.add_argument("--role", choices=ROLES, required=True)
    route.add_argument("--model")
    route.add_argument("--effort")
    route.add_argument("--rationale", required=True)
    auto_route = _subcommand(sub, "node-route-auto", mutate=True)
    auto_route.add_argument("--node-id", required=True)
    auto_route.add_argument("--criticality", type=int, required=True)
    auto_route.add_argument("--determinism", type=int, required=True)
    auto_route.add_argument("--profile-file")
    claim = _subcommand(sub, "node-claim", mutate=True)
    claim.add_argument("--node-id", required=True)
    start = _subcommand(sub, "node-start", mutate=True)
    start.add_argument("--node-id", required=True)
    start.add_argument("--child-id", required=True)
    complete_node = _subcommand(sub, "node-complete", mutate=True)
    complete_node.add_argument("--node-id", required=True)
    complete_node.add_argument("--outcome", choices=("succeeded", "failed"), required=True)
    result = complete_node.add_mutually_exclusive_group()
    result.add_argument("--result")
    result.add_argument("--result-file")
    evidence = complete_node.add_mutually_exclusive_group()
    evidence.add_argument("--evidence")
    evidence.add_argument("--evidence-file")
    complete_node.add_argument("--actual-cost", type=float)
    update = _subcommand(sub, "node-update", mutate=True)
    update.add_argument("--node-id", required=True)
    update.add_argument("--status", choices=NODE_UPDATE_STATUSES)
    update.add_argument("--launch-state", choices=LAUNCH_STATES)
    update.add_argument("--request-id")
    update.add_argument("--child-id")
    update.add_argument("--reconciliation")
    update.add_argument("--result")
    update.add_argument("--evidence")
    update.add_argument("--actual-cost", type=float)
    update.add_argument("--attempt-outcome")
    graph = _subcommand(sub, "graph-validate")
    graph.add_argument("--workflow-id", required=True)
    replan = _subcommand(sub, "graph-replan", mutate=True)
    plan = replan.add_mutually_exclusive_group(required=True)
    plan.add_argument("--plan-json")
    plan.add_argument("--plan-file")
    requirement = _subcommand(sub, "requirement-set", mutate=True)
    requirement.add_argument("--requirement-id", required=True)
    requirement.add_argument("--text", required=True)
    requirement.add_argument("--source", required=True)
    requirement.add_argument("--status", choices=("active", "satisfied", "superseded"), required=True)
    requirement.add_argument("--evidence")
    decision = _subcommand(sub, "decision", mutate=True)
    decision.add_argument("--text", required=True)
    decision.add_argument("--rationale", required=True)
    blocked = _subcommand(sub, "block", mutate=True)
    blocked.add_argument("--node-id")
    blocked.add_argument("--reason", required=True)
    blocked.add_argument("--needed", required=True)
    unblocked = _subcommand(sub, "unblock", mutate=True)
    unblocked.add_argument("--blocker-id", required=True)
    unblocked.add_argument("--resolution", required=True)
    event = _subcommand(sub, "event", mutate=True)
    event.add_argument("--kind", required=True)
    event.add_argument("--message", required=True)
    event.add_argument("--node-id")
    finish = _subcommand(sub, "finish", mutate=True)
    finish.add_argument("--summary", required=True)
    finish.add_argument("--validation", required=True)
    finish.add_argument("--review-waiver")
    complete_workflow = _subcommand(sub, "workflow-complete", mutate=True)
    completion = complete_workflow.add_mutually_exclusive_group(required=True)
    completion.add_argument("--completion-json")
    completion.add_argument("--completion-file")
    abort = _subcommand(sub, "abort", mutate=True)
    abort.add_argument("--reason", required=True)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args, invalid = parse_invocation(build_parser(), argv)
    if args is None:
        return invalid
    try:
        exit_code, code, data, warnings = execute_command(args, StateStore())
        return emit(args.command, code=code, data=data, warnings=warnings, exit_code=exit_code, as_json=args.json)
    except StateError as exc:
        return emit(args.command, code=exc.code, data={"message": str(exc)}, exit_code=exc.exit_code, as_json=args.json)
    except OSError as exc:
        wrapped = StateError("workflow operation failed at the operating-system boundary", code="io_error", exit_code=20)
        wrapped.__cause__ = exc
        return emit(args.command, code=wrapped.code, data={"message": str(wrapped)}, exit_code=wrapped.exit_code, as_json=args.json)
